/* eslint-disable */
// This file is auto-generated by TanStack Router

import { Route as rootRoute } from "./routes/__root";
import { Route as ContactRoute } from "./routes/contact";
import { Route as IndexRoute } from "./routes/index";
import { Route as ServicesRoute } from "./routes/services";

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRoute;
      parentRoute: typeof rootRoute;
    };
    "/services": {
      id: "/services";
      path: "/services";
      fullPath: "/services";
      preLoaderRoute: typeof ServicesRoute;
      parentRoute: typeof rootRoute;
    };
    "/contact": {
      id: "/contact";
      path: "/contact";
      fullPath: "/contact";
      preLoaderRoute: typeof ContactRoute;
      parentRoute: typeof rootRoute;
    };
  }
}

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ServicesRoute,
  ContactRoute,
]);
